### ISSUE TITLE
ボールを消すタイミングの変更とボール周りのバクの確認

### ISSUE THREAD

**Issue by M-634** [M-634/vr_baseball_for_graduation_exhibition#13]
**変更内容**
現在ボールが消えるタイミングは、ピッチャーが投げてボールがIHitBallObjectインターファイスを継承したオブジェットにあたって２秒後に消えるようになっている。それを以下の様に変更すること。

- [x] ボールの速度が限りなく０に近づいたら消す.
- [x] ボールがピッチャー、または球場の客席に落ちたらすぐに消す.

上記の実装が終わったらチェックボックスにチェックを入れてください.

**現状把握しているバグ**

1. ピッチャーが投げた初級のボールが消えず、次の球を投げて来ない時がある.

上記の確認のほどよろしくお願いします.

**Comment by junjun1002** [comment]
ピッチャーが投げた初級のボールが消えず、次の球を投げて来ない時がある.

上記のバグについて
おそらくボールが床を抜けているからだと思われる

**Comment by M-634** [comment]
修正完了
